spring:
  datasource:
    url: jdbc:mysql://160.191.244.248:3307/cms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 2
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    enabled: true

  servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
  auto-tag-classes: true

base:
    url: ${BASE_URL:http://160.191.244.248:8000/}



